local set = vim.opt
vim.notify = require("notify")

set.expandtab = true
set.spell = true
set.spelllang = "en,es"
set.smarttab = true
set.rnu = true
set.number = true
set.hidden = true
set.wrap = false
set.termguicolors = true
set.fileencoding = 'utf-8'
set.showcmd = true
set.showmatch = true
set.tabstop = 2
set.shiftwidth = 2
set.softtabstop = 2
set.expandtab = true
--set.shell = 'pwsh'
--set.shell = 'powershell'
--set.autochdir = true
set.wildmenu = true
set.clipboard = 'unnamedplus'
