# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true 


# Move the directory to the second line
format = """ $sudo\
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$fill\
$package\
$docker_context\
$c\
$container\
$cmake\
$dart\
$dotnet\
$java\
$kotlin\
$lua\
$php\
$python\
$rust\
$golang$nodejs$cmd_duration$time \
$line_break\
$character"""

[fill]
symbol = " "
# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = ' [❯](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
error_symbol = ' [](bold red)'

[nodejs]
format = "[$symbol($version )]($style)"

[git_branch]
symbol = ''
truncation_symbol = ''

[directory]
format = " [$path]($style)[$read_only]($read_only_style) "
read_only = "🔒"
truncate_to_repo = true 

[username]
style_user = 'white bold'
style_root = 'black bold'
format = '[$user >>]($style) '
disabled = false
show_always = true

[cmd_duration]
disabled = false
format = "[$duration]($style) "
style = "yellow"

[time]
disabled = false
format = "[$time]($style) "

[sudo]
disabled = false

[python]
format = "[${symbol}${pyenv_prefix}(${version} )(\\($virtualenv\\) )]($style)"

[golang]
format = "[$symbol ($version )]($style)"
symbol = ""
style = "blue"

[package]
format = "[$symbol$version]($style) "

[java]
format = "[$symbol($version )]($style)"
symbol = "☕ "

[git_metrics]
disabled = false
format = "([+$added]($added_style) )([-$deleted]($deleted_style) )"

[lua]
format = "[$symbol ($version)]($style)"

[docker_context]
format = '[🐋 $context](blue bold)'

[container]
format = '[$symbol \[$name\]]($style) '
